REPORT ZSUM_OF_2_NUMBERS.

DATA OUTPUT TYPE NUMC3.

PARAMETERS: INPUT1 TYPE NUMC2,
            INPUT2 TYPE NUMC2.

CALL FUNCTION 'ZSUM_OF_TWO_NUMBERS'
  EXPORTING
    PINPUT1       = INPUT1
    PINPUT2       = INPUT2
 IMPORTING
   POUTPUT       =  OUTPUT
          .

WRITE : OUTPUT, 'IS THE SUM OF TWO NUMBERS'.